version: "3"
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/home/mantis/Tools/BountyProcess/rabbitmq/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/home/mantis/Tools/BountyProcess/rabbitmq/log/rabbitmq/
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
